import * as React from "react";
import * as Types from "./types";

declare function SectionCarouselV2(props: {
  as?: React.ElementType;
  sectionHeaderV2Variant?: "Base" | "Long Title";
  sectionHeaderV2Label?: React.ReactNode;
  sectionHeaderV2HideTitle?: Types.Visibility.VisibilityConditions;
  sectionHeaderV2Title?: React.ReactNode;
  sectionHeaderV2HideIntroText?: Types.Visibility.VisibilityConditions;
  sectionHeaderV2IntroText?: React.ReactNode;
  sectionHeaderV2ShowScrollIcon?: Types.Visibility.VisibilityConditions;
  sectionHeaderV2ShowLink?: Types.Visibility.VisibilityConditions;
  sectionHeaderV2BtnText?: React.ReactNode;
  sectionHeaderV2BtnLink?: Types.Basic.Link;
  sectionHeaderV2Show2ndIntro?: Types.Visibility.VisibilityConditions;
  sectionHeaderV2SecondIntroText?: React.ReactNode;
  cardV2Alt21Link?: Types.Basic.Link;
  cardV2Alt21Title?: React.ReactNode;
  cardV2Alt21Text?: React.ReactNode;
  cardV2Alt21TextVisibility?: Types.Visibility.VisibilityConditions;
  cardV2Alt21Image?: Types.Asset.Image;
  cardV2Alt21Icon?: Types.Asset.Image;
  cardV2Alt21IconVisibility?: Types.Visibility.VisibilityConditions;
  cardV2Alt21HasModal?: Types.Visibility.VisibilityConditions;
  cardV2Alt21ModalText?: React.ReactNode;
  cardV2Alt22Link?: Types.Basic.Link;
  cardV2Alt22Title?: React.ReactNode;
  cardV2Alt22Text?: React.ReactNode;
  cardV2Alt22TextVisibility?: Types.Visibility.VisibilityConditions;
  cardV2Alt22Image?: Types.Asset.Image;
  cardV2Alt22Icon?: Types.Asset.Image;
  cardV2Alt22IconVisibility?: Types.Visibility.VisibilityConditions;
  cardV2Alt22HasModal?: Types.Visibility.VisibilityConditions;
  cardV2Alt22ModalText?: React.ReactNode;
  cardV2Alt23Link?: Types.Basic.Link;
  cardV2Alt23Title?: React.ReactNode;
  cardV2Alt23Text?: React.ReactNode;
  cardV2Alt23TextVisibility?: Types.Visibility.VisibilityConditions;
  cardV2Alt23Image?: Types.Asset.Image;
  cardV2Alt23Icon?: Types.Asset.Image;
  cardV2Alt23IconVisibility?: Types.Visibility.VisibilityConditions;
  cardV2Alt23HasModal?: Types.Visibility.VisibilityConditions;
  cardV2Alt23ModalText?: React.ReactNode;
}): React.JSX.Element;
